version: '3.9'

services:
  db:
    container_name: todo-db
    image: postgres:14-alpine3.16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=todo@1234
      - POSTGRES_DB=todo-go
    ports:
      - "5438:5432"